apiVersion: v1
kind: Secret
metadata:
  name: notifications-secrets
  namespace: event-management
type: Opaque
stringData:
  JWT_SECRET: "your-jwt-secret-key-here-change-in-production"
  EMAIL_USER: "tipsntricks395@gmail.com"
  EMAIL_PASS: "daik rxsh npnm gnur"
