apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  namespace: event-management
spec:
  type: ClusterIP
  selector:
    app: notifications-service
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8006
