apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-docs-ingress
  namespace: event-management
spec:
  ingressClassName: istio
  rules:
    - host: api-docs.c-282f7f4.kyma.ondemand.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: api-docs
              port:
                number: 8080
  tls:
    - hosts:
      - api-docs.c-282f7f4.kyma.ondemand.com
      secretName: kyma-gateway-certs
