apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graphql-bff-ingress
  namespace: event-management
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  ingressClassName: istio
  rules:
    - host: graphql.c-282f7f4.kyma.ondemand.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: graphql-bff-service
              port:
                number: 4000
  tls:
    - hosts:
      - graphql.c-282f7f4.kyma.ondemand.com
      secretName: kyma-gateway-certs
